### get all cinemas
GET http://localhost:8080/webapi/cinemas

### get all cinemas with params
GET http://localhost:8080/webapi/cinemas?phrase=abc
custom-header: custom-value
Cookie: some-cookie=some-value

### get cinema by id
GET http://localhost:8080/webapi/cinemas/1
Accept: application/xml

### get cinemas playing movie
GET http://localhost:8080/webapi/movies/1/cinemas
Accept: application/json

### create new cinema
POST http://localhost:8080/webapi/cinemas
Content-Type: application/json

{
  "name": "Kino Wisła",
  "logo": "https://www.kinoteka.pl/img/logo.png"
}